name: Rebase Upstream
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 10  # greater than the number of commits you made

#     - uses: imba-tjd/rebase-upstream-action@master
#       with:  # All args are optional
#         upstream: l499477004/JD-scripts
#         branch:   master
#       id: rebase
#       with:
#         upstream: l499477004/JD-scripts
    - run: |        
        git remote add upstream https://github.com/l499477004/JD-scripts.git;
        git fetch upstream master --depth=10;
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
        git config --local user.name  "GitHub Actions";
        git rebase upstream/master;
      shell: bash
    - uses: ad-m/github-push-action@master
      if: steps.rebase.outputs.needs-push
      with:
        force: true
        github_token: ${{ secrets.PAT }}
#         branch: ${{ github.ref }}
