name: Rebase Upstream
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
         persist-credentials: false
         fetch-depth: 0
    - run: |        
        git remote add upstream https://github.com/l499477004/JD-scripts.git;
        git fetch upstream master --depth=10;
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
        git config --local user.name  "GitHub Actions";
        git rebase upstream/master;
      shell: bash
    - uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.PAT }}
        branch: master
