name: Rebase Upstream
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 10  # greater than the number of commits you made
#     - uses: imba-tjd/rebase-upstream-action@master
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#       with:
#         persist-credentials: false
#         fetch-depth: 0  # larger than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
      with:  # All args are optional
        upstream: l499477004/JD-scripts
        branch:   master
#       id: rebase
#       with:
#         upstream: l499477004/JD-scripts
#     - uses: ad-m/github-push-action@master
#       if: steps.rebase.outputs.needs-push
#       with:
#         force: true
#         github_token: ${{ secrets.PAT }}
#         branch: ${{ github.ref }}
